[theme]
base="dark"
primaryColor="#A9DFBF"          # Clove green
backgroundColor="#111111"
secondaryBackgroundColor="#222222"
textColor="#F0F0F0"
font="sans serif"

[server]
enableCORS = true
enableXsrfProtection = false

[browser]
gatherUsageStats = false
